---
language: node_js
node_js:
  - "6"

sudo: false

addons:
  firefox: latest

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bowers cache

before_script:
  - export DISPLAY=:99; sh -e /etc/init.d/xvfb start; sleep 3

before_install:
  - npm config set spin false
  - npm install -g bower
  - bower --version

install:
  - npm install
  - bower install

script:
  - ember try:each
